Indexer/nft metadata
Filemarket-xyz/file-market pull request #33
Opened 2023-04-20 16:31 UTC by w8noot

## Заметки:

- `maxValue` и подобные мета-мета свойства передавать отдельным трейтом с постфиксом
  Пример:
```json
[
  {
    "traitType": "Ranking__max_value",
    "displayType": "number",
    "value": "100"
  },
  {
    "traitType": "Ranking__min_value",
    "displayType": "number",
    "value": "0"
  }
]
```

- `value` всегда строка, но парсится как указано в `displayType`, чтобы не ебаться с бд и в дальнейшем можно разных приколов добиться
```yaml
MetadataProperty:
    type: object
    description: Структура для свойств в метаданных
    properties:
      traitType:
        type: string
        description: Название свойства
      displayType:
        type: string
        description: Тип данных значения
      value:
        type: string
        description: Значение свойства	
```

2023-05-01 18:46 UTC, shleshg requested changes

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230412133337_number.sql
> +    ADD COLUMN number NUMERIC NOT NULL default -1;
а почему на numeric поменялось? строкой же хотели хранить и по апи отдавать

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +    PRIMARY KEY (id),
суррогатный id тут может вогнать в ловушку. метаданные по идее одни на токен, а такая таблица никак не гарантирует уникальность по (collection_address, token_id). а если на эту пару сделать primary key, то ключ позволяет на всех стульях усидеть. ну и сам лишний айдишник тут может начать путать, если в каждой таблице будет свой суррогатный id

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +    metadata_id BIGINT NOT NULL,
та же история, что с token_metadata. получается, что на одни метаданные допустимо несколько hidden_file_metadata. и еще один суррогатный id

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +    PRIMARY KEY (id),
тут проблемы с уникальностью нет. а вот сам этот id новый довольно бесполезен, он просто будет жить в таблице, а давать ничего не будет

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +    PRIMARY KEY (id),
плюс типы TEXT обсудили, что меняем на VARCHAR(255)

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +    PRIMARY KEY (id),
опять бесполезный айдишник

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +    PRIMARY KEY (id),
и еще один

2023-05-01 18:46 UTC, shleshg commented on indexer/migrations/20230419200001_metadata.sql
> +  PRIMARY KEY (id),
и еще один

2023-05-01 18:46 UTC, shleshg commented on indexer/swagger.yaml
> +        description: Значение свойства
maxValue нет

2023-05-02 13:46 UTC, w8noot commented on indexer/swagger.yaml
> +        description: Значение свойства
я не добавил это в коммит случайно) min_value как я понял тоже нужно добавить, так что добавил

2023-05-02 13:54 UTC, w8noot commented on indexer/migrations/20230412133337_number.sql
> +    ADD COLUMN number NUMERIC NOT NULL default -1;
у нас там главная штука с ним это искать максимальное значение, а по строке это делать больно в том числе глазу, так как мы все равно его кастим в нумерик, еще и через регулярку надо пускать. Со строкой было вот так:
 ```
		SELECT encrypted_password
		FROM transfers
		WHERE 
			number ~ '^[0-9]+$'
			AND collection_address=$1
			AND token_id=$2
		ORDER BY number::numeric DESC
		LIMIT 1;
 ```
 
 А так как это нумерик, то в pgx он строкой возвращается.

2023-05-02 14:26 UTC, w8noot commented on indexer/migrations/20230419200001_metadata.sql
> +    PRIMARY KEY (id),
А раз мы у метаданных id убрали, то нам в каждой проперти нужно хранить collection_address и token_id? Или я туплю?

2023-05-02 21:40 UTC, shleshg requested changes

2023-05-02 21:40 UTC, shleshg commented on indexer/internal/repository/tokens.go
> +			traitCountByValue, traitTotal, err := p.GetTraitCount(ctx, tx, prop.TraitType, prop.Value)
вот так умрет вызов, потому что курсор к постгре все еще открыт, а этот вызов запустит новый. важно всегда rows.Close делать прежде чем что-то еще в базе делать

2023-05-03 10:20 UTC, merged