Frontend/wagmi
Filemarket-xyz/file-market pull request #462
Opened 2023-09-23 21:25 UTC by Aleksey-Levin

2023-09-27 15:35 UTC, Santalov requested changes

2023-09-27 15:35 UTC, Santalov commented on packages/frontend/src/app/hooks/useCallContract.ts
> +  return {
Сча ещё пообщался с Аликом и выяснил, что useContractWrite под капотом вызывает simulate, так что не нужно отдельно вызывать его, если хочется в хуках использовать. 
Проверил по исходникам в wagmi есть функция writeContract, и она вызывает всегда prepareWriteContract, а prepare вызывает simulate. Важно, что это именно writeContract из wagmi, а не из viem

2023-09-27 15:35 UTC, Santalov commented on packages/frontend/src/app/processing/utils/error.ts
> +    await client?.simulateContract({
read не нужно симулировать, потому что read это и есть симуляция 
![image](https://github.com/Filemarket-xyz/file-market/assets/34722240/3daf726b-1293-4ce7-8367-aa396e12fb85)

2023-09-27 15:35 UTC, Santalov commented on packages/frontend/src/app/processing/utils/error.ts
> +    // @ts-expect-error
стремные expect error

2023-09-27 15:35 UTC, Santalov commented on packages/frontend/src/app/processing/utils/error.ts
> +    return data
по ощущениям callContractGetter то же самое, что и функция из wagmi/core https://wagmi.sh/core/actions/readContract

2023-09-27 16:19 UTC, Santalov commented on packages/frontend/src/app/hooks/useCallContract.ts
> +  return {
```typescript
function myCallContract<TAbi extends Abi | readonly unknown[], TFunctionName extends string>(config: WriteContractUnpreparedArgs<TAbi, TFunctionName> | WriteContractPreparedArgs<TAbi, TFunctionName>): Promise<WriteContractResult> {
  return writeContract(config)
}
```

2023-09-28 11:19 UTC, Aleksey-Levin commented on packages/frontend/src/app/components/NFT/NFTDeal/helper/wrapButtonActionsFunction.ts
> -        return result
Там return оказывается не нужен

2023-09-28 21:45 UTC, Santalov commented on packages/frontend/src/app/processing/nft-interaction/usePlaceOrder.ts
> +            '0x0000000000000000000000000000000000000000'],
используй константу для таких значений. В ethers был zeroAddress, если в viem нет, то можешь свою определить

2023-09-28 21:45 UTC, Santalov commented on packages/frontend/src/app/config/web3Modal.tsx
> +(window as any).global = window
тоже надо в файл polyfills вынести

2023-09-28 21:45 UTC, Santalov commented on packages/frontend/src/app/processing/utils/error.ts
> +export const callContractGetter = async <T extends Abi, B extends string, R = any>({
не понял, а зачем осталась эта функция?

2023-09-29 15:51 UTC, Santalov requested changes

2023-09-29 15:51 UTC, Santalov commented on packages/frontend/src/app/components/Web3/EnterSeedPhraseDialog/EnterSeedPhraseForm/EnterSeedPhraseForm.tsx
> -import { sha256 } from 'ethereum-cryptography/sha256.js'
пакет удали из зависимостей заодно

2023-09-29 15:51 UTC, Santalov commented on packages/frontend/src/app/utils/crypto/sha256.ts
> +export const sha256 = (data: ArrayBuffer): ArrayBuffer => {
А поч ты решил выбрать наиболее длинный вариант функции из двух. Там можно так сделать:
```typescript
crypto.subtle.digest('SHA-256', data)
```

2023-09-29 15:51 UTC, Santalov commented on packages/frontend/src/app/components/Web3/EnterSeedPhraseDialog/EnterSeedPhraseForm/EnterSeedPhraseForm.tsx
> +                const sha512Value = await fileMarketCrypto.sha512(Buffer.from(mnemonicToEntropy((p)), 'hex'))
Похоже, надо здесь sha256 использовать вместо fileMarketCrypto.sha512

2023-09-29 21:39 UTC, merged