Frontend/derivation fixes
Filemarket-xyz/file-market pull request #48
Opened 2023-05-02 09:58 UTC by ColinMilton

2023-05-02 21:18 UTC, Santalov requested changes

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/BlockchainDataProvider/IBlockchainDataProvider.ts
> +  setGlobalSalt: () => Promise<void>
Такие штуки лучше делать геттерами, возвращающими промис, и не отдавать ответственность за хранение globalSalt провайдеру данных. Это нужно, чтобы пользователям sdk не нужно было реализовывать логику хранения global salt.

Кстати, global salt получается из контракта AccessToken, а не из индексера

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/ContractProvider/ContractProvider.ts
> +export class ContractProvider {
Не интерфейс, но в целом можно потом подумать, как сделать абстракцию под это нормально.
Мб заставлять юзеров SDK тянуть wagmi

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileOwner/HiddenFileOwner.ts
> +  #args: PersistentDerivationArgs
вроде до этого ты такие поля модификатором private предворял

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileBuyer/HiddenFileBuyer.ts
> +    this.#args = [this.seedProvider.seed, blockchainDataProvider.globalSalt, ...this.#tokenFullId]
seed может меняться в зависимости от того, разблокировал чел files wallet или нет, сохранять его тут нельзя

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileOwner/HiddenFileOwner.ts
> +    this.#args = [this.seedProvider.seed, blockchainDataProvider.globalSalt, ...this.#tokenFullId]
нельзя сохранять seed (см коммент выше)

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileOwner/HiddenFileOwner.ts
> +    if (this.address === creator) {
адрес нужно нормализовывать перед сравнением через utils.getAddress

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileOwner/HiddenFileOwner.ts
> +      if (this.address === creator) {
адрес нужно нормализовывать перед сравнением через utils.getAddress

2023-05-02 21:18 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileOwner/HiddenFileOwner.ts
> +      const { priv } = await this.crypto.eftRsaDerivation(...this.#args, dealNumber)
тут видимо ошибка, потому что если owner==creator, то пароль не нужно расшифровывать, так как сделок, где пароль бы зашифровался, ещё не было

2023-05-03 10:40 UTC, ColinMilton commented on packages/frontend/src/app/processing/HiddenFileBuyer/HiddenFileBuyer.ts
> +    this.#args = [this.seedProvider.seed, blockchainDataProvider.globalSalt, ...this.#tokenFullId]
тут не понял
если он не разблокировал то и owner не создастся
и на каждый кошелек (seed) мы делаем отдельного owner, соответственно, всё ок должно быть

2023-05-03 10:41 UTC, ColinMilton commented on packages/frontend/src/app/processing/HiddenFileOwner/HiddenFileOwner.ts
> +  #args: PersistentDerivationArgs
это и есть private, только нативный, а не из TS

2023-05-03 10:43 UTC, ColinMilton commented on packages/frontend/src/app/processing/ContractProvider/ContractProvider.ts
> +export class ContractProvider {
ну я так расчитывал, что будет какой-то конфиг для пользователей SDK, если нет, то надо придумать что-то другое

2023-05-03 11:05 UTC, ColinMilton commented on packages/frontend/src/app/processing/ContractProvider/ContractProvider.ts
> +export class ContractProvider {
ну мне кажется это не большая цена за простоту (в сдк тянуть wagmi)
если без этого, то я знаю способ только через typechain, где побольше писать

2023-05-03 11:39 UTC, Santalov commented on packages/frontend/src/app/processing/ContractProvider/ContractProvider.ts
> +export class ContractProvider {
Да, давай тянуть тогда. Можно в целом в sdk и abi прикладывать

2023-05-03 11:41 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileBuyer/HiddenFileBuyer.ts
> +    this.#args = [this.seedProvider.seed, blockchainDataProvider.globalSalt, ...this.#tokenFullId]
Хм, ну да, можно оставить тогда

2023-05-03 11:42 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileBuyer/HiddenFileBuyer.ts
> +    this.#args = [this.seedProvider.seed, blockchainDataProvider.globalSalt, ...this.#tokenFullId]
Хотя нет, можно создать owner, потом заблочить кошель, и seed станет undefined, но останется сохраненный в Owner, и, если в интерфейсе не хватает проверок, чел сможет выставить на продажу nft с заблокированного аккаунта

2023-05-03 11:47 UTC, Santalov commented on packages/frontend/src/app/processing/HiddenFileProcessorFactory/HiddenFileProcessorFactory.ts
> +    const globalSalt = await this.blockchainDataProvider.getGlobalSalt()
global salt можно сохранять в поле в фабрике при первом создании buyer/owner, так как global salt не меняется никогда

2023-05-03 16:07 UTC, merged