Frontend/errors
Filemarket-xyz/file-market pull request #71
Opened 2023-05-07 18:55 UTC by ColinMilton

2023-05-13 09:02 UTC, Santalov requested changes
Не хендлится ошибка недостаточного баланса и подобные ей:
![image](https://github.com/Filemarket-xyz/file-market/assets/34722240/3e422864-a517-4252-b0d2-fe8cc5262edb)

Для таких ошибок нужно вытаскивать текст из тела ошибки. Стоит при этом учесть, что тело ошибки может быть разным в разных сетях. Нормальных правил под это нет, поэтому просто куча if-else и тестить на разных сетях (в нашем случае, обз надо протестить FVM Hyperspace testnet и FVM Mainnet)

Так же не хендлятся ошибки, возвращаемые контрактами.
![telegram-cloud-photo-size-2-5404456850520393388-y](https://github.com/Filemarket-xyz/file-market/assets/34722240/83c09aaf-f358-4e55-9a9e-156ce0964ae1)

Тут история сложнее, так как там тело ошибки не содержит полезной информации:
![image](https://github.com/Filemarket-xyz/file-market/assets/34722240/479f299d-0b1b-493c-ad1d-63924fe10ecc)

Тут просто contract reverted без причины. У файлкоина есть даже ишу на этот счет. Однако нам для отладки и техподдержки, а так же юзерам, чтобы не впадать в ступор, необходимо получить нормальную ошибку.

Опытным путем выяснилось, что это возможно, если сделать static call метода контракта на фронте.
Делается примерно так:
![image](https://github.com/Filemarket-xyz/file-market/assets/34722240/8dd96cc3-1b38-4dc2-89d0-d27212a64d03)
После ошибку можно будет обработать. 

Ошибку из примера выше можно получить, купив с account1 токен, который заминтил account2, а затем попытавшись заминтить в коллекцию этого токена (то есть заминтить с account1 в коллекцию, owner которой account2). В идеале нужно получить ошибку "Ownable: caller is not the owner".

Чтобы так можно было сделать, нужно убрать проверку на owner в списке коллекций для минта: src/app/stores/CollectionAndTokenListStore.ts:92

2023-05-16 18:26 UTC, ColinMilton commented on packages/frontend/src/app/processing/utils/error.ts
> +  while (receipt === null) {
добавил таймаут на 5 минут
много, но зная как этот файлкоин работает, лучше уж так, я считаю
энивей до этого вообще бесконечно висела модалка с загрузкой, если транза отвалилась
так хотя бы 5 минут повисит в крайнем случае )))

2023-05-17 11:43 UTC, Santalov approved these changes

2023-05-17 11:43 UTC, Santalov commented on packages/frontend/src/app/processing/utils/error.ts
> +    if (receipt === null) continue
бесполезная проверка (на работоспособность никак не влияет, но просто)

2023-05-17 11:43 UTC, merged